<template>
    <div class="w-full flex justify-center">
        <h2>Favorites</h2>
    </div>
    <CocktailCard :cocktail="cocktailDetails1"></CocktailCard>
    <CocktailCard :cocktail="cocktailDetails2"></CocktailCard>
    <CocktailCard :cocktail="cocktailDetails3"></CocktailCard>
    <CocktailCard :cocktail="cocktailDetails4"></CocktailCard>
    <CocktailCard :cocktail="cocktailDetails5"></CocktailCard>
    <CocktailCard :cocktail="cocktailDetails6"></CocktailCard>

</template>
<script setup>
import { reactive } from "vue";
import CocktailCard from '@/components/CocktailCard.vue'

const cocktailDetails1 = reactive({
      "idDrink": "15300",
      "strDrink": "3-Mile Long Island Iced Tea",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Collins Glass",
      "strInstructions": "Fill 14oz glass with ice and alcohol. Fill 2/3 glass with cola and remainder with sweet & sour. Top with dash of bitters and lemon wedge.",
      "strInstructionsES": null,
      "strInstructionsDE": "Füllen Sie ein 12 cl. Glas mit Eis und Alkohol. Füllen Sie 2/3 des Glases mit Cola und den Rest mit Süß-Sauer. Mit einem Schuss Bitter und Zitronenkeil garnieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Riempi un bicchiere da almeno 400ml con ghiaccio e alcol. Riempire i restanti 2/3 di bicchiere di cola e il resto di bevanda sweet & sour. Completare con un pizzico di bitter e uno spicchio di limone.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rrtssw1472668972.jpg",
      "strIngredient1": "Gin",
      "strIngredient2": "Light rum",
      "strIngredient3": "Tequila",
      "strIngredient4": "Triple sec",
      "strIngredient5": "Vodka",
      "strIngredient6": "Coca-Cola",
      "strIngredient7": "Sweet and sour",
      "strIngredient8": "Bitters",
      "strIngredient9": "Lemon",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/2 oz",
      "strMeasure2": "1/2 oz",
      "strMeasure3": "1/2 oz",
      "strMeasure4": "1/2 oz",
      "strMeasure5": "1/2 oz",
      "strMeasure6": "1/2 oz",
      "strMeasure7": "1-2 dash ",
      "strMeasure8": "1 wedge ",
      "strMeasure9": "Garnish with",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-08-31 19:42:52"
});

const cocktailDetails2 = reactive({
      "idDrink": "11766",
      "strDrink": "Midnight Cowboy",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
      "strInstructionsES": null,
      "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vsxxwy1441208133.jpg",
      "strIngredient1": "Bourbon",
      "strIngredient2": "Dark rum",
      "strIngredient3": "Heavy cream",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1/2 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-02 16:35:33"
    });
const cocktailDetails3 = reactive({
      "idDrink": "11766",
      "strDrink": "Midnight Cowboy",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
      "strInstructionsES": null,
      "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vsxxwy1441208133.jpg",
      "strIngredient1": "Bourbon",
      "strIngredient2": "Dark rum",
      "strIngredient3": "Heavy cream",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1/2 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-02 16:35:33"
    });
const cocktailDetails4 = reactive({
      "idDrink": "14956",
      "strDrink": "Jello shots",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Shot",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Shot glass",
      "strInstructions": "Boil 3 cups of water then add jello. Mix jello and water until jello is completely disolved. Add the two cups of vodka and mix together. Pour mixture into plastic shot glasses and chill until firm. Then, eat away...",
      "strInstructionsES": null,
      "strInstructionsDE": "Kochen Sie 3 Tassen Wasser und fügen Sie dann Jello hinzu. Jello und Wasser mischen, bis Jello vollständig aufgelöst ist. Fügen Sie die beiden Tassen Wodka hinzu und mischen Sie sie zusammen. Die Mischung in Kunststoff-Schnapsgläser füllen und kühl stellen. Dann iss es weg.....",
      "strInstructionsFR": null,
      "strInstructionsIT": "Fai bollire 3 tazze d'acqua e aggiungi la gelatina.\r\nMescolare la gelatina e l'acqua fino a quando la gelatina è completamente sciolta.\r\nAggiungere le due tazze di vodka e mescolale.\r\nVersare il composto in bicchierini di plastica e raffreddare fino a quando non si rassoda.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/l0smzo1504884904.jpg",
      "strIngredient1": "Vodka",
      "strIngredient2": "Jello",
      "strIngredient3": "Water",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 cups ",
      "strMeasure2": "3 packages ",
      "strMeasure3": "3 cups ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-08 16:35:04"
    });
const cocktailDetails5 = reactive({
      "idDrink": "17828",
      "strDrink": "Tipperary",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Nick and Nora Glass",
      "strInstructions": "Stir over ice. Strain into chilled glass. Cut a wide swath of orange peel, and express the orange oils over the drink. Discard orange twist.",
      "strInstructionsES": null,
      "strInstructionsDE": "Über das Eis geben. In ein gekühltes Glas abseihen. Schneiden Sie einen breiten Streifen Orangenschale und geben Sie die Orangenöle über das Getränk. Entsorgen Sie den orangefarbenen Twist.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Mescola sul ghiaccio.\r\nFiltrare in un bicchiere freddo.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/b522ek1521761610.jpg",
      "strIngredient1": "Irish Whiskey",
      "strIngredient2": "Sweet Vermouth",
      "strIngredient3": "Green Chartreuse",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz",
      "strMeasure2": "1 oz",
      "strMeasure3": "1/2 oz",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2018-03-22 23:33:30"
    });
const cocktailDetails6 = reactive({
      "idDrink": "11170",
      "strDrink": "Brandy Sour",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Whiskey sour glass",
      "strInstructions": "Shake brandy, juice of lemon, and powdered sugar with ice and strain into a whiskey sour glass. Decorate with the lemon slice, top with the cherry, and serve.",
      "strInstructionsES": null,
      "strInstructionsDE": "Brandy, Zitronensaft und Puderzucker mit Eis schütteln und in ein Whiskey Sour Glas abseihen. Mit der Zitronenscheibe dekorieren, mit der Kirsche garnieren und servieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare brandy, succo di limone e zucchero a velo con ghiaccio e filtrare in un bicchiere da whisky sour. Decorare con la fetta di limone, guarnire con la ciliegia e servire.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/b1bxgq1582484872.jpg",
      "strIngredient1": "Brandy",
      "strIngredient2": "Lemon",
      "strIngredient3": "Powdered sugar",
      "strIngredient4": "Lemon",
      "strIngredient5": "Cherry",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz ",
      "strMeasure2": "Juice of 1/2 ",
      "strMeasure3": "1/2 tsp ",
      "strMeasure4": "1/2 slice ",
      "strMeasure5": "1 ",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "Yes",
      "dateModified": "2017-09-02 16:35:40"
    });

</script>
